// Generated by CoffeeScript 1.6.3
(function() {
  var Linje, LinjeList;

  Linje = (function() {
    function Linje(dep) {
      this.dep = dep;
      this.id = this.dep.name + "|" + dep.direction;
      if (this.dep.name.match(/\w+ \d+/)) {
        this.name = dep.name.split(" ")[1];
      } else {
        this.name = dep.name.substr(0, 3);
      }
      this.name = this.name.trim();
      this.origName = dep.name;
      this.color = {
        'fg': dep.bgColor,
        'bg': dep.fgColor
      };
      this.direction = dep.direction;
      this.times = [];
      this.addTime(this.dep);
    }

    Linje.prototype.toDate = function(date, time) {
      var dateParts, timeParts;
      dateParts = date.split('-');
      return timeParts = time.split(':');
    };

    Linje.prototype.addTime = function(dep) {
      var date;
      if ((dep.rtTime != null) && (dep.rtDate != null)) {
        return date = toDate(dep.rtDate, dep.rtTime);
      }
    };

    Linje.prototype.getTimes = function() {
      var list;
      return list = [];
    };

    Linje.prototype.getTimeLeft = function(date) {};

    Linje.prototype.getTimeString = function(time) {
      var timeLeft;
      timeLeft = moment(time).diff(moment(), 'minutes');
      if (timeLeft < 1) {
        return 'Nu';
      }
      if (timeLeft > 10) {
        return time.toLocaleTimeString().substr(0, 5);
      }
      return timeLeft + 'm';
    };

    return Linje;

  })();

  LinjeList = (function() {
    function LinjeList() {
      this.list = [];
    }

    LinjeList.prototype.push = function(dep) {};

    return LinjeList;

  })();

}).call(this);
